/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FormCadastroFuncionarioController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Murilo Melo
 */
public class FormCadastroFuncionarioView extends javax.swing.JFrame {

    private final FormCadastroFuncionarioController controller;

    /**
     * Creates new form TelaFormCadastro
     */
    public FormCadastroFuncionarioView() {
        initComponents();
        controller = new FormCadastroFuncionarioController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNomeNovoFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoSalvarTelaCadastro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoSalarioNovoFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoTelefoneNovoFuncionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoEnderecoNovoFuncionario = new javax.swing.JTextField();
        campoFuncaoNovoFuncionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome Funcionario:");

        jLabel2.setText("Função:");

        botaoSalvarTelaCadastro.setText("Salvar");
        botaoSalvarTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarTelaCadastroActionPerformed(evt);
            }
        });

        jLabel3.setText("Salário (somente números)");

        jLabel4.setText("Telefone (somente números)");

        jLabel5.setText("Endereço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botaoSalvarTelaCadastro)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNomeNovoFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoSalarioNovoFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoTelefoneNovoFuncionario)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoEnderecoNovoFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFuncaoNovoFuncionario, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoFuncaoNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSalarioNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefoneNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEnderecoNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(botaoSalvarTelaCadastro)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarTelaCadastroActionPerformed
        try {
            controller.salvaNovoFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(FormCadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoSalvarTelaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroFuncionarioView().setVisible(true);
            }
        });
    }

    public JTextField getCampoFuncaoNovoFuncionario() {
        return campoFuncaoNovoFuncionario;
    }

    public void setCampoFuncaoNovoFuncionario(JTextField campoFuncaoNovoFuncionario) {
        this.campoFuncaoNovoFuncionario = campoFuncaoNovoFuncionario;
    }

    public void setCampoFuncaoNovoFuncionario(JPasswordField campoFuncaoNovoFuncionario) {
        this.campoFuncaoNovoFuncionario = campoFuncaoNovoFuncionario;
    }

    public JTextField getCampoNomeNovoFuncionario() {
        return campoNomeNovoFuncionario;
    }

    public void setCampoNomeNovoFuncionario(JTextField campoNomeNovoUsuario) {
        this.campoNomeNovoFuncionario = campoNomeNovoUsuario;
    }

    public JTextField getCampoEnderecoNovoFuncionario() {
        return campoEnderecoNovoFuncionario;
    }

    public void setCampoEnderecoNovoFuncionario(JTextField campoEnderecoNovoFuncionario) {
        this.campoEnderecoNovoFuncionario = campoEnderecoNovoFuncionario;
    }

    public JTextField getCampoSalarioNovoFuncionario() {
        return campoSalarioNovoFuncionario;
    }

    public void setCampoSalarioNovoFuncionario(JTextField campoSalarioNovoFuncionario) {
        this.campoSalarioNovoFuncionario = campoSalarioNovoFuncionario;
    }

    public JTextField getCampoTelefoneNovoFuncionario() {
        return campoTelefoneNovoFuncionario;
    }

    public void setCampoTelefoneNovoFuncionario(JTextField campoTelefoneNovoFuncionario) {
        this.campoTelefoneNovoFuncionario = campoTelefoneNovoFuncionario;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarTelaCadastro;
    private javax.swing.JTextField campoEnderecoNovoFuncionario;
    private javax.swing.JTextField campoFuncaoNovoFuncionario;
    private javax.swing.JTextField campoNomeNovoFuncionario;
    private javax.swing.JTextField campoSalarioNovoFuncionario;
    private javax.swing.JTextField campoTelefoneNovoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
